# Generated by Django 4.0.1 on 2022-09-15 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keys',
            old_name='enc_ptivate_key',
            new_name='enc_public_key',
        ),
    ]
