# Generated by Django 4.0.1 on 2022-09-15 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apikey', '0002_rename_enc_ptivate_key_keys_enc_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
