# Generated by Django 4.0.1 on 2022-09-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0004_alter_keys_private_key_alter_keys_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='enc_private_key',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='keys',
            name='enc_public_key',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='keys',
            name='private_key',
            field=models.CharField(max_length=53),
        ),
        migrations.AlterField(
            model_name='keys',
            name='public_key',
            field=models.CharField(max_length=53),
        ),
    ]
