# Generated by Django 4.0.1 on 2022-06-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_storage',
            old_name='imagess',
            new_name='files',
        ),
    ]
