# Generated by Django 4.0.1 on 2022-06-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0002_rename_imagess_file_storage_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="file_storage",
            name="anyone_upload",
            field=models.BooleanField(default=True),
        ),
    ]
