# Generated by Django 4.0.1 on 2022-08-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0005_filestorage_files_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filestorage',
            old_name='files_image',
            new_name='files_name',
        ),
    ]
