# Generated by Django 4.0.1 on 2022-08-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0006_rename_files_image_filestorage_files_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstoragevolume',
            name='volume_in_kb',
            field=models.BigIntegerField(default=31457280),
        ),
    ]
