# Generated by Django 4.0.1 on 2022-09-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0008_alter_folder_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="filestorage",
            name="idd",
            field=models.CharField(default="vxc48sx7f", max_length=30),
        ),
    ]
