# Generated by Django 4.0.1 on 2022-09-20 02:08

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0010_alter_userstoragevolume_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filestorage',
            name='files',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='store/%Y/%m/%d'),
        ),
    ]
